# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: emerald

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'The highly-customizable Hugo Academic theme powered by Hugo Blox Builder. Easily create your personal academic website.'
    twitter: 'GetResearchDev'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    logo:
      text: "Eshwar Venugopal"

# Site footer
footer:
  copyright:
    notice: ''
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false

# Custom CSS
custom_css:
  - css/custom.css

# Citation style
publications:
  citation_style: apa  # Change this value to your preferred style

#avatar
avatar:
  shape: square  # or 'square' if you prefer
  # Add these lines to control image quality
  quality: 100   # Highest quality (1-100)

# If the above doesn't work, try adding to config.yaml or config.toml
imaging:
  quality: 100
  resampleFilter: CatmullRom
  anchor: Smart